import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Navbar from '@/components/Navbar'

export default function Home() {
  return (
    <>
      <Head>
        <title>MOTI | Panasian Kitchen</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/moti2.png" />
      </Head>
      <main>
        <Navbar />
        <section className={styles.heroBox}>
          <div className={styles.heroInfo}>
            <div className={styles.heroTitle}>
              Почувствуйте вкус <span>паназиатской</span> кухни
            </div>
            <button className={styles.actionBtn}>
              Забронировать стол
            </button>
          </div>

          <img src="./images/hero-moti.png" alt="Hero Image" className={styles.heroImg} />
        </section>
      </main>
    </>
  )
}
